In [1]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.matlib
%matplotlib inline
import quantecon as qe
import scipy.optimize as optimize
import scipy.sparse as sparse
from quantecon import compute_fixed_point
from quantecon.markov import DiscreteDP
import copy
from Leapfrogging import leapfrogging
lf = leapfrogging()
from RLS import rls_class
rls = rls_class()

In [2]:
ss = lf.cSS(lf.nC)
ESS = lf.cESS(lf.nC)
Gtau= lambda ss, ESS, tau: lf.state_recursion(ss,ESS, tau)  
ESS, TAU, out=rls.solve(Gtau,ss.copy(),ESS.copy(),lf.stage_index)

tau in state_recursion: 10
bases in state_recusion: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
in T
after:
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
in T-1
after:
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
in T-2
after:
[1 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
in mod==1
after:
[1 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
in mod==0
after:
[1 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
in mod==2
xxx here we go:
yup x2x
0 0 2 1.6666666666666665
test_i: 1
in first if
variables 1:
0
1
-3.1125000000000003
0.0
84.92774586780568
0.0
in first if
variables 1:
1
0
0.05826474833571327
0.0
19.91385755758604
23.02635755758604
in elif
variables 2:
0.9646468502067397
0.01837561375888752
0.0
22.21230328965953
ss: {'P1': 0.9646468502067397, 'vN1': 0, 'vI1': 0, 'P2': 0.01837561375888752, 'vN2': 22.21230328965953, 'vI2': 22.21230328965953} 
yup x2x
0 1 2 1.6666666666666665
test_i: 2
in first if
v

In [4]:
np.maximum(5.-5.,0)

0.0

In [7]:
0

0

In [12]:
P1,vN1,vI1,P2,vN2,vI2 = [1], 2, [3], 4, 5, 6

for v in [P1,vN1,vI1,P2,vN2,vI2]:
    if isinstance(v,list):
        print(v)
        exec(f'{v} = {v[0]}')
        print(v)
eq = {'P1':P1, 'vN1':vN1, 'vI1':vI1, 'P2':P2, 'vN2':vN2, 'vI2':vI2}
print(eq)

[1]


SyntaxError: cannot assign to literal (<string>, line 1)

In [9]:
np.zeros(int(N*(N+1)*(2*N+1)/6),dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.zeros((1,int(N*(N+1)*(2*N+1)/6)),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
testESS[1]

[0, 0, 0, 0, 0, 1]

In [22]:
type(np.nonzero((ESS['esr'][0]-ESS['esr'][0])!=0))

tuple

In [8]:
ESS

{'index': array([[[29, 28, 21, 7],
         [None, 26, 23, 10],
         [None, None, 17, 13],
         [None, None, None, 1]],
 
        [[None, 27, 22, 8],
         [None, 25, 24, 11],
         [None, None, 18, 14],
         [None, None, None, 2]],
 
        [[None, None, 19, 9],
         [None, None, 20, 12],
         [None, None, 16, 15],
         [None, None, None, 3]],
 
        [[None, None, None, 4],
         [None, None, None, 5],
         [None, None, None, 6],
         [None, None, None, 0]]], dtype=object),
 'esr': array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1.]),
 'bases': array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]])}