In [1]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.matlib
%matplotlib inline
import quantecon as qe
import scipy.optimize as optimize
import scipy.sparse as sparse
from quantecon import compute_fixed_point
from quantecon.markov import DiscreteDP
import copy
from Leapfrogging import leapfrogging
lf = leapfrogging()
from RLS import rls_class
rls = rls_class()

In [2]:
ss1 = lf.cSS(lf.nC)
ESS1 = lf.cESS(lf.nC)
Gtau= lambda ss, ESS, tau: lf.state_recursion(ss,ESS, tau)  
ESS, TAU, out=rls.solve(Gtau,ss1.copy(),ESS1.copy(),lf.stage_index)


ESR[0]['esr']  :
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1]
ESR[0]['bases']:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


c:\Users\Jonat\Documents\Polit\Dynamic programing\Term paper\Github\Dynamic-Programming-Leapfrogging\RLS.py:92: RuntimeWarning: divide by zero encountered in remainder
  temp_xi = np.mod(addESS['esr'][i] + R,addESS['bases'][i])
c:\Users\Jonat\Documents\Polit\Dynamic programing\Term paper\Github\Dynamic-Programming-Leapfrogging\RLS.py:92: RuntimeWarning: invalid value encountered in remainder
  temp_xi = np.mod(addESS['esr'][i] + R,addESS['bases'][i])


ESR[1000]['esr']  :
[-1 -1 -1 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0 -1 -1 -1 -1 -1  0 -1 -1
 -1 -1 -1 -1 -1 -1]
ESR[1000]['bases']:
[0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 0 0 0 0 0 2 0 0 0 0 0 0 2 0]
ESR[2000]['esr']  :
[-1 -1 -1 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0 -1 -1 -1 -1 -1  0 -1 -1
 -1 -1 -1 -1 -1 -1]
ESR[2000]['bases']:
[0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 0 0 0 0 0 2 0 0 0 0 0 0 2 0]
ESR[3000]['esr']  :
[-1 -1 -1 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0 -1 -1 -1 -1 -1  0 -1 -1
 -1 -1 -1 -1 -1 -1]
ESR[3000]['bases']:
[0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 0 0 0 0 0 2 0 0 0 0 0 0 2 0]
ESR[4000]['esr']  :
[-1 -1 -1 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0 -1 -1 -1 -1 -1  0 -1 -1
 -1 -1 -1 -1 -1 -1]
ESR[4000]['bases']:
[0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 0 0 0 0 0 2 0 0 0 0 0 0 2 0]
ESR[5000]['esr']  :
[-1 -1 -1 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0 -1 -1 -1 -1 -1  0 -1 -1
 -1 -1 -1 -1 -1 -1]
ESR[5000]['bases']:
[0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 0 0 0 0 0 2 0 0 0 0 0 0 2 0]
ESR[6000]['esr']  :
[-1 -

In [4]:
TAU

array([], dtype=float64)

In [6]:
for i in range(len(pstar1)):
    for j in range(len(pstar2)):
        if i > 1 and j > 1 and pstar1[i] >= 0 and pstar2[j] >= 0 and pstar1[i] <= 1 and pstar2[j] <= 1:
            print('ok')

ok


In [10]:
if 2 > 1 and 2 > 1 and pstar1[2] >= 0 and pstar2[2] >= 0 and pstar1[2] <= 1 and pstar2[2] <= 1:
    print('ok')

ok


In [9]:
tau[0] = {}
tau[0]['EQs'] = EQs

In [10]:
tau

array([{'EQs': array([[[None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None]],

       [[None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None]],

       [[None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None]],

       [[None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None]],

       [[None, None, None, None, None, None],
        [No

In [12]:
P1,vN1,vI1,P2,vN2,vI2 = [1], 2, [3], 4, 5, 6

for v in [P1,vN1,vI1,P2,vN2,vI2]:
    if isinstance(v,list):
        print(v)
        exec(f'{v} = {v[0]}')
        print(v)
eq = {'P1':P1, 'vN1':vN1, 'vI1':vI1, 'P2':P2, 'vN2':vN2, 'vI2':vI2}
print(eq)

[1]


SyntaxError: cannot assign to literal (<string>, line 1)

In [9]:
np.zeros(int(N*(N+1)*(2*N+1)/6),dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.full((2, 5), -1.)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
testESS[1]

[0, 0, 0, 0, 0, 1]

In [22]:
type(np.nonzero((ESS['esr'][0]-ESS['esr'][0])!=0))

tuple

In [8]:
ESS

{'index': array([[[29, 28, 21, 7],
         [None, 26, 23, 10],
         [None, None, 17, 13],
         [None, None, None, 1]],
 
        [[None, 27, 22, 8],
         [None, 25, 24, 11],
         [None, None, 18, 14],
         [None, None, None, 2]],
 
        [[None, None, 19, 9],
         [None, None, 20, 12],
         [None, None, 16, 15],
         [None, None, None, 3]],
 
        [[None, None, None, 4],
         [None, None, None, 5],
         [None, None, None, 6],
         [None, None, None, 0]]], dtype=object),
 'esr': array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1.]),
 'bases': array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]])}