In [1]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.matlib
%matplotlib inline
import quantecon as qe
import scipy.optimize as optimize
import scipy.sparse as sparse
from quantecon import compute_fixed_point
from quantecon.markov import DiscreteDP
import copy
from Leapfrogging import leapfrogging
lf = leapfrogging()
from RLS import rls_class
import torch
rls = rls_class()

In [2]:
ss1 = lf.cSS(lf.nC)
ESS1 = lf.cESS(lf.nC)
Gtau= lambda ss, ESS, tau: lf.state_recursion(ss,ESS, tau)  
ESS, TAU, out=rls.solve(Gtau,ss1.copy(),ESS1.copy(),lf.stage_index)


ESR[0]['esr']  :
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1]
ESR[0]['bases']:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
ESR[1000]['esr']  :
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0  0  1 -1  1  1 -1 -1 -1 -1 -1  0 -1 -1
 -1 -1 -1 -1 -1 -1]
ESR[1000]['bases']:
[0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
ESR[2000]['esr']  :
[-1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1  1  0  0 -1  1 -1 -1 -1 -1 -1 -1 -1 -1
  1 -1 -1 -1 -1 -1]
ESR[2000]['bases']:
[0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 2 0 0 0 0 0]
ESR[3000]['esr']  :
[-1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1  0 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1  1 -1]
ESR[3000]['bases']:
[0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 0 0 0 0 0 2 0 0 0 0 0 0 2 0]
ESR[4000]['esr']  :
[-1 -1 -1 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1  0  1 -1 -1 -1 -1 -1  1 -1 -1
 -1 -1 -1 -1  1 -1]
ESR[4000]['bases']:
[0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 0 0 0 0 0 2 0 0 0 0 0 0 2 0]
ESR[5000]['esr']  :
[-1 -1 -1 -

In [14]:
number_of_equilibria=np.size(TAU)
T=torch.numel(torch.tensor(lf.stage_index))

y = np.zeros(T)
for i in range(T):
    y[i] = sum(TAU==i)
V = np.zeros((number_of_equilibria,2))
MPEesr = np.empty(number_of_equilibria,dtype='object')
for iEQ in range(number_of_equilibria):
    V[iEQ,0]=out[iEQ]['V1']
    V[iEQ,1]=out[iEQ]['V2']
    MPEesr[iEQ]=out[iEQ]['MPEesr']

In [27]:
[el[0] for el in V]

[0.0,
 1.1206054520452,
 0.0,
 0.0,
 1.1206054520452,
 0.033238511361438516,
 0.0,
 1.1206054520452,
 0.0,
 0.0,
 1.1206054520452,
 0.033238511361438516,
 0.0,
 1.1206054520452,
 0.0,
 0.0,
 1.1206054520452,
 0.033238511361438516,
 0.0,
 1.1206054520452,
 0.0,
 0.0,
 1.1206054520452,
 0.0,
 0.0,
 1.1206054520452,
 0.033238511361438516,
 0.0,
 1.1206054520452,
 0.0,
 0.0,
 1.1206054520452,
 0.033238511361438516,
 0.0,
 1.1206054520452,
 0.0,
 0.0,
 1.1206054520452,
 0.033238511361438516,
 0.0,
 1.1206054520452,
 0.0,
 0.0,
 1.1206054520452,
 0.0,
 0.0,
 1.1206054520452,
 0.033238511361438516,
 0.0,
 1.1206054520452,
 0.0,
 0.0,
 1.1206054520452,
 0.033238511361438516,
 0.0,
 1.1206054520452,
 0.0,
 0.0,
 1.1206054520452,
 0.033238511361438516,
 0.0,
 1.1206054520452,
 0.0,
 0.0,
 1.1206054520452,
 0.033238511361438516,
 0.0,
 1.1206054520452,
 0.033238511361438516,
 0.0,
 1.1206054520452,
 0.033238511361438516,
 0.0,
 1.1206054520452,
 0.033238511361438516,
 0.0,
 1.1206054520452,
 0.03