In [1]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.matlib
%matplotlib inline
import quantecon as qe
import scipy.optimize as optimize
import scipy.sparse as sparse
from quantecon import compute_fixed_point
from quantecon.markov import DiscreteDP
import copy
from Leapfrogging import leapfrogging
lf = leapfrogging()
from RLS import rls_class
rls = rls_class()

In [2]:
ss = lf.cSS(lf.nC)
ESS = lf.cESS(lf.nC)
Gtau= lambda ss, ESS, tau: lf.state_recursion(ss,ESS, tau)  

In [3]:
ESS, TAU, out=rls.solve(Gtau,ss,ESS,lf.stage_index)

c:\Users\Jonat\Documents\Polit\Dynamic programing\Term paper\Github\Dynamic-Programming-Leapfrogging\Leapfrogging.py:54: RuntimeWarning: divide by zero encountered in double_scalars
  self.K = lambda c: self.k0+self.k1/(1+self.k2*c) # investment cost of state of the art production cost c
c:\Users\Jonat\Documents\Polit\Dynamic programing\Term paper\Github\Dynamic-Programming-Leapfrogging\Leapfrogging.py:198: RuntimeWarning: invalid value encountered in double_scalars
  d = b**2 - 4*a*c
c:\Users\Jonat\Documents\Polit\Dynamic programing\Term paper\Github\Dynamic-Programming-Leapfrogging\Leapfrogging.py:201: RuntimeWarning: invalid value encountered in double_scalars
  pstar = [0, 1, -c/b] # xxx no idea what happens here


 counte: 0 
ESR[0]['esr']  :
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
ESR[0]['bases']:
[1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


IndexError: index 10 is out of bounds for axis 0 with size 10

In [5]:
min([28, 29])

28

In [9]:
np.zeros(int(N*(N+1)*(2*N+1)/6),dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.zeros((1,int(N*(N+1)*(2*N+1)/6)),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
testESS[1]

[0, 0, 0, 0, 0, 1]

In [22]:
type(np.nonzero((ESS['esr'][0]-ESS['esr'][0])!=0))

tuple

In [8]:
ESS

{'index': array([[[29, 28, 21, 7],
         [None, 26, 23, 10],
         [None, None, 17, 13],
         [None, None, None, 1]],
 
        [[None, 27, 22, 8],
         [None, 25, 24, 11],
         [None, None, 18, 14],
         [None, None, None, 2]],
 
        [[None, None, 19, 9],
         [None, None, 20, 12],
         [None, None, 16, 15],
         [None, None, None, 3]],
 
        [[None, None, None, 4],
         [None, None, None, 5],
         [None, None, None, 6],
         [None, None, None, 0]]], dtype=object),
 'esr': array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1.]),
 'bases': array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]])}