In [1]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.matlib
%matplotlib inline
import quantecon as qe
import scipy.optimize as optimize
import scipy.sparse as sparse
from quantecon import compute_fixed_point
from quantecon.markov import DiscreteDP
import copy
from Leapfrogging import leapfrogging
lf = leapfrogging()
from RLS import rls_class
rls = rls_class()

In [2]:
ss = lf.cSS(lf.nC)
ESS = lf.cESS(lf.nC)
Gtau= lambda ss, ESS, tau: lf.state_recursion(ss,ESS, tau)  
ESS, TAU, out=rls.solve(Gtau,ss.copy(),ESS.copy(),lf.stage_index)

tau in state_recursion: 10
in T
after:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
in T-1
after:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
in T-2
in last_interior
after:
[0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
in mod==1
after:
[0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
{'P1': 0, 'vN1': 0, 'vI1': 0, 'P2': 0, 'vN2': 0, 'vI2': 0}
in mod==0
c,p,ic: (1.6666666666666665, 1.0, 2) 
 in ic1: 0 
{'P1': 0, 'vN1': 0, 'vI1': -3.1125000000000003, 'P2': 0, 'vN2': 91.37357920113901, 'vI2': 88.26107920113901}
 in ic1: 1 
{'P1': 0, 'vN1': 0, 'vI1': -3.1125000000000003, 'P2': 0, 'vN2': 57.199968379362524, 'vI2': 54.08746837936253}
 in ic2: 0 
parts of H2:
[[     29 4849756 7340144 6488175]
 [7471207 6815860 7274600 6029410]
 [6488161 6488179 6881396 7536748]
 [7078005 7798829 3407926 5046318]]
-1
{'P1': 0, 'vN1': 0, 'vI1': 0, 'P2': 0, 'vN2': 0, 'vI2': 0}
variables: 
0.0
3.1125000000000003
0.0
{'P1': 0, 'vN1': 6.504098081669047

c:\Users\Jonat\Documents\Polit\Dynamic programing\Term paper\Github\Dynamic-Programming-Leapfrogging\RLS.py:79: RuntimeWarning: divide by zero encountered in remainder
  temp_xi = np.mod(addESS['esr'][i] + R,addESS['bases'][i])
c:\Users\Jonat\Documents\Polit\Dynamic programing\Term paper\Github\Dynamic-Programming-Leapfrogging\Leapfrogging.py:214: RuntimeWarning: invalid value encountered in long_scalars
  out = np.floor(x/y) # xxx dot notation before: out=floor(x./y)
c:\Users\Jonat\Documents\Polit\Dynamic programing\Term paper\Github\Dynamic-Programming-Leapfrogging\RLS.py:79: RuntimeWarning: invalid value encountered in remainder
  temp_xi = np.mod(addESS['esr'][i] + R,addESS['bases'][i])
c:\Users\Jonat\Documents\Polit\Dynamic programing\Term paper\Github\Dynamic-Programming-Leapfrogging\Leapfrogging.py:214: RuntimeWarning: divide by zero encountered in long_scalars
  out = np.floor(x/y) # xxx dot notation before: out=floor(x./y)


In [5]:
N = 4
np.zeros(int(N*(N+1)*(2*N+1)/6),dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.full((1, int(N*(N+1)*(2*N+1)/6)), -1.)[0]

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1.])

In [12]:
P1,vN1,vI1,P2,vN2,vI2 = [1], 2, [3], 4, 5, 6

for v in [P1,vN1,vI1,P2,vN2,vI2]:
    if isinstance(v,list):
        print(v)
        exec(f'{v} = {v[0]}')
        print(v)
eq = {'P1':P1, 'vN1':vN1, 'vI1':vI1, 'P2':P2, 'vN2':vN2, 'vI2':vI2}
print(eq)

[1]


SyntaxError: cannot assign to literal (<string>, line 1)

In [9]:
np.zeros(int(N*(N+1)*(2*N+1)/6),dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.full((2, 5), -1.)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
testESS[1]

[0, 0, 0, 0, 0, 1]

In [22]:
type(np.nonzero((ESS['esr'][0]-ESS['esr'][0])!=0))

tuple

In [8]:
ESS

{'index': array([[[29, 28, 21, 7],
         [None, 26, 23, 10],
         [None, None, 17, 13],
         [None, None, None, 1]],
 
        [[None, 27, 22, 8],
         [None, 25, 24, 11],
         [None, None, 18, 14],
         [None, None, None, 2]],
 
        [[None, None, 19, 9],
         [None, None, 20, 12],
         [None, None, 16, 15],
         [None, None, None, 3]],
 
        [[None, None, None, 4],
         [None, None, None, 5],
         [None, None, None, 6],
         [None, None, None, 0]]], dtype=object),
 'esr': array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1.]),
 'bases': array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]])}