In [1]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.matlib
%matplotlib inline
import quantecon as qe
import scipy.optimize as optimize
import scipy.sparse as sparse
from quantecon import compute_fixed_point
from quantecon.markov import DiscreteDP
import copy
from Leapfrogging import leapfrogging
lf = leapfrogging()
from RLS import rls_class
rls = rls_class()

SyntaxError: 'break' outside loop (Leapfrogging.py, line 605)

In [ ]:
ss = lf.cSS(lf.nC)
ESS = lf.cESS(lf.nC)
Gtau= lambda ss, ESS, tau: lf.state_recursion(ss,ESS, tau)  
ESS, TAU, out=rls.solve(Gtau,ss.copy(),ESS.copy(),lf.stage_index)

tau in state_recursion: 10
bases in state_recusion: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
bases after T,-1,-2: [1 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
in mod==2
in mod==2
ESR[0]['esr']  :
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
ESR[0]['bases']:
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
ESS.bases [1 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 1 1 1 1 1 3 3 3 3 1 1 1 3 1] 
ESS.esr [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 
change index: 28
tau after count: 2


In [7]:
0

0

In [12]:
P1,vN1,vI1,P2,vN2,vI2 = [1], 2, [3], 4, 5, 6

for v in [P1,vN1,vI1,P2,vN2,vI2]:
    if isinstance(v,list):
        print(v)
        exec(f'{v} = {v[0]}')
        print(v)
eq = {'P1':P1, 'vN1':vN1, 'vI1':vI1, 'P2':P2, 'vN2':vN2, 'vI2':vI2}
print(eq)

[1]


SyntaxError: cannot assign to literal (<string>, line 1)

In [9]:
np.zeros(int(N*(N+1)*(2*N+1)/6),dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.zeros((1,int(N*(N+1)*(2*N+1)/6)),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
testESS[1]

[0, 0, 0, 0, 0, 1]

In [22]:
type(np.nonzero((ESS['esr'][0]-ESS['esr'][0])!=0))

tuple

In [8]:
ESS

{'index': array([[[29, 28, 21, 7],
         [None, 26, 23, 10],
         [None, None, 17, 13],
         [None, None, None, 1]],
 
        [[None, 27, 22, 8],
         [None, 25, 24, 11],
         [None, None, 18, 14],
         [None, None, None, 2]],
 
        [[None, None, 19, 9],
         [None, None, 20, 12],
         [None, None, 16, 15],
         [None, None, None, 3]],
 
        [[None, None, None, 4],
         [None, None, None, 5],
         [None, None, None, 6],
         [None, None, None, 0]]], dtype=object),
 'esr': array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1.]),
 'bases': array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]])}