In [1]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.matlib
%matplotlib inline
import quantecon as qe
import scipy.optimize as optimize
import scipy.sparse as sparse
from quantecon import compute_fixed_point
from quantecon.markov import DiscreteDP
from Leapfrogging import leapfrogging
lf = leapfrogging()
from RLS import rls_class
rls = rls_class()

In [2]:
ss = lf.cSS(lf.nC)
ESS = lf.cESS(lf.nC)
Gtau= lambda ss, ESS, tau: lf.state_recursion(ss,ESS, tau)  

In [3]:
ESS, TAU, out=rls.solve(Gtau,ss,ESS,lf.stage_index)

c:\Users\Jonat\Documents\Polit\Dynamic programing\Term paper\Github\Dynamic-Programming-Leapfrogging\Leapfrogging.py:54: RuntimeWarning: divide by zero encountered in double_scalars
  self.K = lambda c: self.k0+self.k1/(1+self.k2*c) # investment cost of state of the art production cost c
c:\Users\Jonat\Documents\Polit\Dynamic programing\Term paper\Github\Dynamic-Programming-Leapfrogging\Leapfrogging.py:198: RuntimeWarning: invalid value encountered in double_scalars
  d = b**2 - 4*a*c
c:\Users\Jonat\Documents\Polit\Dynamic programing\Term paper\Github\Dynamic-Programming-Leapfrogging\Leapfrogging.py:201: RuntimeWarning: invalid value encountered in double_scalars
  pstar = [0, 1, -c/b] # xxx no idea what happens here


ESR[10000]['esr']  :
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
ESR[10000]['bases']:
[[1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
ESR[20000]['esr']  :
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
ESR[20000]['bases']:
[[1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
ESR[30000]['esr']  :
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
ESR[30000]['bases']:
[[1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
ESR[40000]['esr']  :
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
ESR[40000]['bases']:
[[1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
ESR[50000]['esr']  :
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
ESR[50000]['bases']:
[[1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [ ]:
# below here runs without too many errors

In [ ]:
# Data containers
# These work fine
ss = lf.cSS(lf.nC)
ESS = lf.cESS(lf.nC)
Gtau= lambda ss, ESS, tau: lf.state_recursion(ss,ESS, tau)  

# broken:

# ESS, TAU, out=rls.solve(Gtau,ss,ESS,mp.stage_index)



In [31]:
out = np.empty(4)
out[:] = np.NaN
out

array([nan, nan, nan, nan])

IndexError: index 5 is out of bounds for axis 0 with size 4

In [35]:
out

array([nan,  4., nan, nan])

In [26]:
out[:]

[4, 4, 4]