In [1]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.matlib
%matplotlib inline
import quantecon as qe
import scipy.optimize as optimize
import scipy.sparse as sparse
from quantecon import compute_fixed_point
from quantecon.markov import DiscreteDP
from Leapfrogging import leapfrogging
lf = leapfrogging()

In [2]:
# Data containers

ss = lf.cSS(lf.nC)
ESS = lf.cESS(lf.nC)


In [6]:
print(np.shape(ss))

(4,)


In [4]:
print(ss[3]['nEQ'])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
