In [8]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.matlib
%matplotlib inline
import quantecon as qe
import scipy.optimize as optimize
import scipy.sparse as sparse
from quantecon import compute_fixed_point
from quantecon.markov import DiscreteDP
from Leapfrogging import leapfrogging
lf = leapfrogging()

In [9]:
# Data containers

ss = lf.cSS(lf.nC)
ESS = lf.cESS(lf.nC)


In [11]:
print(ss)

[{'EQs': array([[[None, None, None,
         {'eq': {'P1': [], 'vN1': [], 'vI1': [], 'P2': [], 'vN2': [], 'vI2': []}},
         None],
        [None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None]],

       [[None, None, None, None, None],
        [None, None, None,
         {'eq': {'P1': [], 'vN1': [], 'vI1': [], 'P2': [], 'vN2': [], 'vI2': []}},
         None],
        [None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None]],

       [[None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None,
         {'eq': {'P1': [], 'vN1': [], 'vI1': [], 'P2': [], 'vN2': [], 'vI2': []}},
         None],
        [None, None, None, None, None],
        [None, None, None, None, None]],

       [[None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None],
       

In [30]:
print(ss[3]['nEQ'])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
